package com.imotion.dslam.business.service;

import com.imotion.dslam.business.CRONIOBUIConstant;
import com.imotion.dslam.business.CRONIOBUIServiceConstant;
import com.selene.arch.base.MFTIConstant;

public interface CRONIOBUIExecuteBusinessServiceConstants {
	
	// BusinessExecuteService types
	long 	CTE_BUSINESS_EXECUTE_SERVICE_TYPE 		= CRONIOBUIServiceConstant.CTE_CRONIO_APP_BUS_EXECUTE_SERVICE_SUBTYPE | CRONIOBUIConstant.CTE_CRONIO_APP_BUSINESS_SERVICE_TYPE;
	String 	CTE_BUSINESS_EXECUTE_SERVICE_HEX_TYPE 	= Long.toHexString(CTE_BUSINESS_EXECUTE_SERVICE_TYPE);
	String 	CTE_BUSINESS_EXECUTE_SERVICE_NAME 		= "CRONIOBUIExecuteBusinessService";

	// RANGE CONSTANTS
	long	CTE_BUSINESS_EXECUTE_SERVICE_RANGE_TRACE = CTE_BUSINESS_EXECUTE_SERVICE_TYPE | MFTIConstant.CTE_MFT_RANGE_TRACE;

	//METHODS
	String 	METHOD_EXECUTE_PROJECT 					= "EXECUTE_PROJECT";
	String 	METHOD_UPDATE_FINISH_EXECUTE			= "UPDATE_FINISH_EXECUTE";
	String 	METHOD_ADD_EXECUTION 					= "ADD_EXECUTION";
	String 	METHOD_GET_EXECUTION_LOGS				= "GET_EXECUTION_LOGS";
	String  METHOD_GET_ALL_EXECUTIONS_BY_PROJECT_ID	= "GET_ALL_EXCUTIONS_BY_PROJECT_ID";
	
	//CONTEXT
	String 	EXECUTE_DATA 					= "EXECUTE_DATA";
	String 	EXECUTIONS_BY_PROJECT_LIST_DATA = "EXECUTIONS_BY_PROJECT_LIST_DATA";
	String 	EXECUTION_DATA 					= "EXECUTION_DATA";
	String  EXECUTIONS_DATA					= "EXECUTIONS_DATA";
	String  EXECUTION_LOGS_DATA				= "EXECUTION_LOGS_DATA";
	String  NODE_LISTS_DATA					= "NODE_LISTS_DATA";
	
}
