package com.imotion.dslam.front.business.desktop.client.view.event;

public interface CRONIOBusDesktopPreferencesEventTypes {
	
	public enum EVENT_TYPE {
		OPEN_FINAL_SECTION_EVENT,
		SAVE_SECTION_TEMPORARILY_EVENT,
		//SHOW_PROJECT_INFO,
		//SECTION_MODIFIED,
		CONNECTION_SAVED, 
		NEW_CONNECTION,
		EDIT_CONNECTION,
		CONNECTION_CREATED,
		OPEN_PROJECTS_PAGE,
		//EDIT_PROJECT_PROPERTIES,
		//SAVE_PROJECT,
		//SAVE_ALL_PROJECTS, 
		//OPEN_EVENT,
		//EXECUTE
	}
	
}
