package com.imotion.dslamstudio.client.widget;

public interface EXTGWTDSLAMIXMLExamples {

	String SHOW_EXAMPLE = ""
			+ "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
			+ "<runtime-data xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" display-level=\"normal\" xsi:noNamespaceSchemaLocation=\"file:cli_show_output.xsd\">\n"
			+ "	  <hierarchy name=\"show\" type=\"static\">\n"
			+ " <hierarchy name=\"equipment\" type=\"static\">\n"
			+ "   <hierarchy name=\"slot\" type=\"static\">\n"
			+ "   	<instance>\n"
			+ "    <res-id name=\"slot\" short-name=\"slot\"  type=\"Equipm::SlotIndexEquipm::SlotIndex\">nt-a</res-id> \n"
			+ "    <info name=\"actual-type\" short-name=\"actual-type\" type=\"Equipm::ActBoardType\">nant-a</info>  \n "
			+ "    <info name=\"oper-status\" short-name=\"enabled\" type=\"Equipm::OperStatus\">yes</info>  \n "
			+ "    <info name=\"error-status\" short-name=\"error-status\" type=\"Equipm::OperError\">no-error</info>  \n "
			+ "    <info name=\"availability\" short-name=\"availability\" type=\"Equipm::AvailStatus\">available</info>  \n "
			+ "    <info name=\"lt-restart-num\" short-name=\"restrt-cnt\" type=\"Counter\">0</info>  \n "
			+ "  </instance>\n"
			+ "  <instance>\n"
			+ " <res-id name=\"slot\" short-name=\"slot\"  type=\"Equipm::SlotIndexEquipm::SlotIndex\">nt-b</res-id>\n"
			+ "<info name=\"actual-type\" short-name=\"actual-type\" type=\"Equipm::ActBoardType\">nant-a</info>  \n "
			+ " <info name=\"oper-status\" short-name=\"enabled\" type=\"Equipm::OperStatus\">no</info>  \n "
			+ "<info name=\"error-status\" short-name=\"error-status\" type=\"Equipm::OperError\">no-error</info>  \n "
			+ "<info name=\"availability\" short-name=\"availability\" type=\"Equipm::AvailStatus\">offline</info>  \n "
			+ "<info name=\"lt-restart-num\" short-name=\"restrt-cnt\" type=\"Counter\">0</info>  \n "
			+ "</instance>\n"
			+ "<instance>\n"
			+ "<res-id name=\"slot\" short-name=\"slot\"  type=\"Equipm::SlotIndexEquipm::SlotIndex\">lt:1/1/1</res-id>\n"
			+ "<info name=\"actual-type\" short-name=\"actual-type\" type=\"Equipm::ActBoardType\">nvlt-n</info>  \n "
			+ "				          <info name=\"oper-status\" short-name=\"enabled\" type=\"Equipm::OperStatus\">yes</info>  \n "
			+ "<info name=\"error-status\" short-name=\"error-status\" type=\"Equipm::OperError\">no-error</info>  \n "
			+ "<info name=\"availability\" short-name=\"availability\" type=\"Equipm::AvailStatus\">available</info>  \n "
			+ " <info name=\"lt-restart-num\" short-name=\"restrt-cnt\" type=\"Counter\">0</info>  \n "
			+ " </instance>\n"
			+ " <instance>\n"
			+ "   <res-id name=\"slot\" short-name=\"slot\"  type=\"Equipm::SlotIndexEquipm::SlotIndex\">lt:1/1/2</res-id>\n"
			+ " <info name=\"actual-type\" short-name=\"actual-type\" type=\"Equipm::ActBoardType\">nvlt-n</info>  \n "
			+ " <info name=\"oper-status\" short-name=\"enabled\" type=\"Equipm::OperStatus\">yes</info>  \n "
			+ " <info name=\"error-status\" short-name=\"error-status\" type=\"Equipm::OperError\">no-error</info>  \n "
			+ " <info name=\"availability\" short-name=\"availability\" type=\"Equipm::AvailStatus\">available</info>  \n "
			+ " <info name=\"lt-restart-num\" short-name=\"restrt-cnt\" type=\"Counter\">0</info>  \n "
			+ "  </instance>\n"
			+ "  </hierarchy>\n"
			+ "  </hierarchy>\n"
			+ " </runtime-data> \n";

}
