package com.imotion.dslam.front.business.desktop.client.event;

public interface CRONIOBusDesktopPreferencesEventTypes {
	
	public enum EVENT_TYPE {
		OPEN_FINAL_SECTION_EVENT,
		SAVE_SECTION_TEMPORARILY_EVENT,
		SHOW_PREFERENCES_INFO,
		SECTION_MODIFIED,
		SECTION_SELECTED,
		PREFERENCES_SAVED, 
		NEW_CONNECTION,
		EDIT_CONNECTION,
		CONNECTION_CREATED,
		OPEN_PROJECTS_PAGE,
		SAVE_PREFERENCES,
	}
	
}
