package com.imotion.dslam.front.business.desktop.client.event;

public interface CRONIOBusDesktopProjectEventTypes {
	
	public enum EVENT_TYPE {
		OPEN_FINAL_SECTION_EVENT,
		OPEN_PREFERENCES_EVENT,
		SAVE_SECTION_TEMPORARILY_EVENT,
		SHOW_PROJECT_INFO,
		SECTION_MODIFIED,
		SECTION_SELECTED,
		PROJECT_SAVED, 
		NEW_PROJECT,
		PROJECT_CREATED,
		NODELIST_CREATED,
		EDIT_PROJECT_PROPERTIES,
		SAVE_PROJECT,
		SAVE_ALL_PROJECTS, 
		OPEN_EVENT,
		ADD_EXECUTION,
		EXECUTE,
		ADD_EXECUTION_LOGS,
		ADD_FILTERED_LOGS,
		GET_PROCESS_NODELISTS,
		GET_NODELIST_ID,
		GET_MACHINE_TYPES,
		DUPLICATE_NODELIST_ERROR
	}
	
}
